### ISSUE TITLE
Review: Required Changes

### ISSUE THREAD

**Issue by tahseenzahra** [jfoyarzo/ToDo-list#2]
Hy Felipe! Your code is excellent you can make some changes to enhance its working.

- it would be great if you make a line over to task when they are checked as in the given design
- Clear button is not working can you please fix that
- You can split your code in modules

**Comment by jfoyarzo** [comment]
Thank you for your feedback! In the latest version, the mentioned issues were fixed 😸 
Happy Coding! 😃
